<?php

use Illuminate\Database\Seeder;

use App\State;
use App\Municipality;


class MunicipalitiesSeeder extends Seeder
{
    protected $municipalities = [
        ['state' => 'AMAZONAS',  'name' => 'Alto Orinoco'],
        ['state' => 'AMAZONAS',  'name' => 'Atabapo'],
        ['state' => 'AMAZONAS',  'name' => 'Atures'],
        ['state' => 'AMAZONAS',  'name' => 'Autana'],
        ['state' => 'AMAZONAS',  'name' => 'Manapiare'],
        ['state' => 'AMAZONAS',  'name' => 'Maroa'],
        ['state' => 'AMAZONAS',  'name' => 'Río Negro'],
        
        ['state' => 'ANZOATEGUI',  'name' => 'Anaco'],
        ['state' => 'ANZOATEGUI',  'name' => 'Aragua'],
        ['state' => 'ANZOATEGUI',  'name' => 'Diego Bautista Urbaneja'],
        ['state' => 'ANZOATEGUI',  'name' => 'Fernando Peñalver'],
        ['state' => 'ANZOATEGUI',  'name' => 'Francisco del Carmen Carvajal'],
        ['state' => 'ANZOATEGUI',  'name' => 'Francisco de Miranda'],
        ['state' => 'ANZOATEGUI',  'name' => 'Guanipa'],
        ['state' => 'ANZOATEGUI',  'name' => 'Guanta'],
        ['state' => 'ANZOATEGUI',  'name' => 'Independencia'],
        ['state' => 'ANZOATEGUI',  'name' => 'José Gregorio Monagas'],
        ['state' => 'ANZOATEGUI',  'name' => 'Juan Antonio Sotillo'],
        ['state' => 'ANZOATEGUI',  'name' => 'Juan Manuel Cajigal'],
        ['state' => 'ANZOATEGUI',  'name' => 'Libertad'],
        ['state' => 'ANZOATEGUI',  'name' => 'Manuel Ezequiel Bruzual'],
        ['state' => 'ANZOATEGUI',  'name' => 'Pedro María Freites'],
        ['state' => 'ANZOATEGUI',  'name' => 'Píritu'],
        ['state' => 'ANZOATEGUI',  'name' => 'San Juan de Capistrano'],
        ['state' => 'ANZOATEGUI',  'name' => 'Santa Ana'],
        ['state' => 'ANZOATEGUI',  'name' => 'Simón Bolívar'],
        ['state' => 'ANZOATEGUI',  'name' => 'Simón Rodríguez'],
        ['state' => 'ANZOATEGUI',  'name' => 'Sir Arthur Mc Gregor'],
        
        ['state' => 'APURE', 'name' =>  'Achaguas'],
        ['state' => 'APURE', 'name' =>  'Biruaca'],
        ['state' => 'APURE', 'name' =>  'Muñoz'],
        ['state' => 'APURE', 'name' =>  'Pedro Camejo'],
        ['state' => 'APURE', 'name' =>  'San Fernando'],
        ['state' => 'APURE', 'name' =>  'Páez'],
        ['state' => 'APURE', 'name' =>  'Rómulo Gallegos'],
        
        ['state' => 'ARAGUA', 'name' => 'Bolívar'],
        ['state' => 'ARAGUA', 'name' => 'Camatagua'],
        ['state' => 'ARAGUA', 'name' => 'Francisco Linares Alcántara'],
        ['state' => 'ARAGUA', 'name' => 'Girardot'],
        ['state' => 'ARAGUA', 'name' => 'José Ángel Lamas'],
        ['state' => 'ARAGUA', 'name' => 'José Félix Ribas'],
        ['state' => 'ARAGUA', 'name' => 'José Rafael Revenga'],
        ['state' => 'ARAGUA', 'name' => 'Libertador'],
        ['state' => 'ARAGUA', 'name' => 'Mario Briceño Iragorry'],
        ['state' => 'ARAGUA', 'name' => 'Ocumare de la Costa de Oro'],
        ['state' => 'ARAGUA', 'name' => 'San Casimiro'],
        ['state' => 'ARAGUA', 'name' => 'San Sebastián'],
        ['state' => 'ARAGUA', 'name' => 'Santiago Mariño'],
        ['state' => 'ARAGUA', 'name' => 'Santos Michelena'],
        ['state' => 'ARAGUA', 'name' => 'Sucre'],
        ['state' => 'ARAGUA', 'name' => 'Tovar'],
        ['state' => 'ARAGUA', 'name' => 'Urdaneta'],
        ['state' => 'ARAGUA', 'name' => 'Zamora'],
        
        ['state' => 'BARINAS', 'name' => 'Alberto Arvelo Torrealba'],
        ['state' => 'BARINAS', 'name' => 'Andrés Eloy Blanco'],
        ['state' => 'BARINAS', 'name' => 'Antonio José de Sucre'],
        ['state' => 'BARINAS', 'name' => 'Arismendi'],
        ['state' => 'BARINAS', 'name' => 'Barinas'],
        ['state' => 'BARINAS', 'name' => 'Bolívar'],
        ['state' => 'BARINAS', 'name' => 'Cruz Paredes'],
        ['state' => 'BARINAS', 'name' => 'Ezequiel Zamora'],
        ['state' => 'BARINAS', 'name' => 'Obispos'],
        ['state' => 'BARINAS', 'name' => 'Pedraza'],
        ['state' => 'BARINAS', 'name' => 'Rojas'],
        ['state' => 'BARINAS', 'name' => 'Sosa'],

        ['state' => 'BOLIVAR', 'name' => 'Caroní'],
        ['state' => 'BOLIVAR', 'name' => 'Cedeño'],
        ['state' => 'BOLIVAR', 'name' => 'El Callao'],
        ['state' => 'BOLIVAR', 'name' => 'Gran Sabana'],
        ['state' => 'BOLIVAR', 'name' => 'Heres'],
        ['state' => 'BOLIVAR', 'name' => 'Padre Pedro Chien'],
        ['state' => 'BOLIVAR', 'name' => 'Piar'],
        ['state' => 'BOLIVAR', 'name' => 'Angostura (Raúl Leoni)'],
        ['state' => 'BOLIVAR', 'name' => 'Roscio'],
        ['state' => 'BOLIVAR', 'name' => 'Sifontes'],
        ['state' => 'BOLIVAR', 'name' => 'Sucre'],

        ['state' => 'CARABOBO', 'name' => 'Bejuma'],
        ['state' => 'CARABOBO', 'name' => 'Carlos Arvelo'],
        ['state' => 'CARABOBO', 'name' => 'Diego Ibarra'],
        ['state' => 'CARABOBO', 'name' => 'Guacara'],
        ['state' => 'CARABOBO', 'name' => 'Juan José Mora'],
        ['state' => 'CARABOBO', 'name' => 'Libertador'],
        ['state' => 'CARABOBO', 'name' => 'Los Guayos'],
        ['state' => 'CARABOBO', 'name' => 'Miranda'],
        ['state' => 'CARABOBO', 'name' => 'Montalbán'],
        ['state' => 'CARABOBO', 'name' => 'Naguanagua'],
        ['state' => 'CARABOBO', 'name' => 'Puerto Cabello'],
        ['state' => 'CARABOBO', 'name' => 'San Diego'],
        ['state' => 'CARABOBO', 'name' => 'San Joaquín'],
        ['state' => 'CARABOBO', 'name' => 'Valencia'],

        ['state' => 'COJEDES', 'name' => 'Anzoátegui'],
        ['state' => 'COJEDES', 'name' => 'Pao de San Juan Bautista'],
        ['state' => 'COJEDES', 'name' => 'Tinaquillo'],
        ['state' => 'COJEDES', 'name' => 'Girardot'],
        ['state' => 'COJEDES', 'name' => 'Lima Blanco'],
        ['state' => 'COJEDES', 'name' => 'Ricaurte'],
        ['state' => 'COJEDES', 'name' => 'Rómulo Gallegos'],
        ['state' => 'COJEDES', 'name' => 'Ezequiel Zamora (Cojedes)'],
        ['state' => 'COJEDES', 'name' => 'Tinaco'],

        ['state' => 'DISTRITO CAPITAL', 'name' => 'Libertador'],

        ['state' => 'FALCON', 'name' => 'Acosta'],
        ['state' => 'FALCON', 'name' => 'Bolívar'],
        ['state' => 'FALCON', 'name' => 'Buchivacoa'],
        ['state' => 'FALCON', 'name' => 'Cacique Manaure'],
        ['state' => 'FALCON', 'name' => 'Carirubana'],
        ['state' => 'FALCON', 'name' => 'Colina'],
        ['state' => 'FALCON', 'name' => 'Dabajuro'],
        ['state' => 'FALCON', 'name' => 'Democracia'],
        ['state' => 'FALCON', 'name' => 'Falcón'],
        ['state' => 'FALCON', 'name' => 'Federación'],
        ['state' => 'FALCON', 'name' => 'Jacura'],
        ['state' => 'FALCON', 'name' => 'Los Taques'],
        ['state' => 'FALCON', 'name' => 'Mauroa'],
        ['state' => 'FALCON', 'name' => 'Miranda'],
        ['state' => 'FALCON', 'name' => 'Monseñor Iturriza'],
        ['state' => 'FALCON', 'name' => 'Palmasola'],
        ['state' => 'FALCON', 'name' => 'Petit'],
        ['state' => 'FALCON', 'name' => 'Píritu'],
        ['state' => 'FALCON', 'name' => 'San Francisco'],
        ['state' => 'FALCON', 'name' => 'José Laurencio Silva'],
        ['state' => 'FALCON', 'name' => 'Sucre'],
        ['state' => 'FALCON', 'name' => 'Tocópero'],
        ['state' => 'FALCON', 'name' => 'Unión'],
        ['state' => 'FALCON', 'name' => 'Urumaco'],
        ['state' => 'FALCON', 'name' => 'Zamora'],

        ['state' => 'GUARICO', 'name' => 'Camaguán'],
        ['state' => 'GUARICO', 'name' => 'Chaguaramas'],
        ['state' => 'GUARICO', 'name' => 'El Socorro'],
        ['state' => 'GUARICO', 'name' => 'Francisco de Miranda'],
        ['state' => 'GUARICO', 'name' => 'José Félix Ribas'],
        ['state' => 'GUARICO', 'name' => 'José Tadeo Monagas'],
        ['state' => 'GUARICO', 'name' => 'Juan Germán Roscio'],
        ['state' => 'GUARICO', 'name' => 'Julián Mellado'],
        ['state' => 'GUARICO', 'name' => 'Las Mercedes'],
        ['state' => 'GUARICO', 'name' => 'Leonardo Infante'],
        ['state' => 'GUARICO', 'name' => 'Ortiz'],
        ['state' => 'GUARICO', 'name' => 'Pedro Zaraza'],
        ['state' => 'GUARICO', 'name' => 'San Jerónimo de Guayabal'],
        ['state' => 'GUARICO', 'name' => 'San José de Guaribe'],
        ['state' => 'GUARICO', 'name' => 'Santa María de Ipire'],

        ['state' => 'LARA', 'name' => 'Andrés Eloy Blanco'],
        ['state' => 'LARA', 'name' => 'Crespo'],
        ['state' => 'LARA', 'name' => 'Morán'],
        ['state' => 'LARA', 'name' => 'Palavecino'],
        ['state' => 'LARA', 'name' => 'Simón Planas'],
        ['state' => 'LARA', 'name' => 'Torres'],
        ['state' => 'LARA', 'name' => 'Urdaneta'],
        ['state' => 'LARA', 'name' => 'Iribarren'],
        ['state' => 'LARA', 'name' => 'Jiménez'],

        ['state' => 'MERIDA', 'name' => 'Alberto Adriani'],
        ['state' => 'MERIDA', 'name' => 'Antonio Pinto Salinas'],
        ['state' => 'MERIDA', 'name' => 'Andrés Bello'],
        ['state' => 'MERIDA', 'name' => 'Aricagua'],
        ['state' => 'MERIDA', 'name' => 'Arzobispo Chacón'],
        ['state' => 'MERIDA', 'name' => 'Campo Elías'],
        ['state' => 'MERIDA', 'name' => 'Caracciolo Parra Olmedo'],
        ['state' => 'MERIDA', 'name' => 'Cardenal Quintero'],
        ['state' => 'MERIDA', 'name' => 'Guaraque'],
        ['state' => 'MERIDA', 'name' => 'Julio César Salas'],
        ['state' => 'MERIDA', 'name' => 'Justo Briceño'],
        ['state' => 'MERIDA', 'name' => 'Libertador'],
        ['state' => 'MERIDA', 'name' => 'Miranda'],
        ['state' => 'MERIDA', 'name' => 'Obispo Ramos de Lora'],
        ['state' => 'MERIDA', 'name' => 'Padre Noguera'],
        ['state' => 'MERIDA', 'name' => 'Pueblo Llano'],
        ['state' => 'MERIDA', 'name' => 'Rangel'],
        ['state' => 'MERIDA', 'name' => 'Rivas Dávila'],
        ['state' => 'MERIDA', 'name' => 'Santos Marquina'],
        ['state' => 'MERIDA', 'name' => 'Sucre'],
        ['state' => 'MERIDA', 'name' => 'Tovar'],
        ['state' => 'MERIDA', 'name' => 'Tulio Febres Cordero'],
        ['state' => 'MERIDA', 'name' => 'Zea'],

        ['state' => 'MIRANDA', 'name' => 'Acevedo'],
        ['state' => 'MIRANDA', 'name' => 'Andrés Bello'],
        ['state' => 'MIRANDA', 'name' => 'Baruta'],
        ['state' => 'MIRANDA', 'name' => 'Brión'],
        ['state' => 'MIRANDA', 'name' => 'Buroz'],
        ['state' => 'MIRANDA', 'name' => 'Carrizal'],
        ['state' => 'MIRANDA', 'name' => 'Chacao'],
        ['state' => 'MIRANDA', 'name' => 'Cristóbal Rojas'],
        ['state' => 'MIRANDA', 'name' => 'El Hatillo'],
        ['state' => 'MIRANDA', 'name' => 'Guaicaipuro'],
        ['state' => 'MIRANDA', 'name' => 'Independencia'],
        ['state' => 'MIRANDA', 'name' => 'Lander'],
        ['state' => 'MIRANDA', 'name' => 'Los Salias'],
        ['state' => 'MIRANDA', 'name' => 'Páez'],
        ['state' => 'MIRANDA', 'name' => 'Paz Castillo'],
        ['state' => 'MIRANDA', 'name' => 'Pedro Gual'],
        ['state' => 'MIRANDA', 'name' => 'Plaza'],
        ['state' => 'MIRANDA', 'name' => 'Simón Bolívar'],
        ['state' => 'MIRANDA', 'name' => 'Urdaneta'],
        ['state' => 'MIRANDA', 'name' => 'Sucre'],
        ['state' => 'MIRANDA', 'name' => 'Zamora'],

        ['state' => 'MONAGAS', 'name' => 'Acosta'],
        ['state' => 'MONAGAS', 'name' => 'Aguasay'],
        ['state' => 'MONAGAS', 'name' => 'Bolívar'],
        ['state' => 'MONAGAS', 'name' => 'Caripe'],
        ['state' => 'MONAGAS', 'name' => 'Cedeño'],
        ['state' => 'MONAGAS', 'name' => 'Ezequiel Zamora'],
        ['state' => 'MONAGAS', 'name' => 'Libertador'],
        ['state' => 'MONAGAS', 'name' => 'Maturín'],
        ['state' => 'MONAGAS', 'name' => 'Piar'],
        ['state' => 'MONAGAS', 'name' => 'Punceres'],
        ['state' => 'MONAGAS', 'name' => 'Santa Bárbara'],
        ['state' => 'MONAGAS', 'name' => 'Sotillo'],
        ['state' => 'MONAGAS', 'name' => 'Uracoa'],

        ['state' => 'NUEVA ESPARTA', 'name' => 'Antolín del Campo'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Arismendi'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Díaz'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'García'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Gómez'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Maneiro'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Marcano'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Mariño'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Macanao'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Tubores'],
        ['state' => 'NUEVA ESPARTA', 'name' => 'Villalba'],

        ['state' => 'PORTUGUESA', 'name' => 'Araure'],
        ['state' => 'PORTUGUESA', 'name' => 'Agua Blanca'],
        ['state' => 'PORTUGUESA', 'name' => 'Esteller'],
        ['state' => 'PORTUGUESA', 'name' => 'Guanare'],
        ['state' => 'PORTUGUESA', 'name' => 'Guanarito'],
        ['state' => 'PORTUGUESA', 'name' => 'Monseñor José Vicente de Unda'],
        ['state' => 'PORTUGUESA', 'name' => 'Ospino'],
        ['state' => 'PORTUGUESA', 'name' => 'Páez'],
        ['state' => 'PORTUGUESA', 'name' => 'Papelón'],
        ['state' => 'PORTUGUESA', 'name' => 'San Genaro de Boconoíto'],
        ['state' => 'PORTUGUESA', 'name' => 'San Rafael de Onoto'],
        ['state' => 'PORTUGUESA', 'name' => 'Santa Rosalía'],
        ['state' => 'PORTUGUESA', 'name' => 'Sucre'],
        ['state' => 'PORTUGUESA', 'name' => 'Turén'],

        ['state' => 'SUCRE', 'name' => 'Andrés Eloy Blanco'],
        ['state' => 'SUCRE', 'name' => 'Andrés Mata'],
        ['state' => 'SUCRE', 'name' => 'Arismendi'],
        ['state' => 'SUCRE', 'name' => 'Benítez'],
        ['state' => 'SUCRE', 'name' => 'Bermúdez'],
        ['state' => 'SUCRE', 'name' => 'Bolívar'],
        ['state' => 'SUCRE', 'name' => 'Cajigal'],
        ['state' => 'SUCRE', 'name' => 'Cruz Salmerón Acosta'],
        ['state' => 'SUCRE', 'name' => 'Libertador'],
        ['state' => 'SUCRE', 'name' => 'Mariño'],
        ['state' => 'SUCRE', 'name' => 'Mejía'],
        ['state' => 'SUCRE', 'name' => 'Montes'],
        ['state' => 'SUCRE', 'name' => 'Ribero'],
        ['state' => 'SUCRE', 'name' => 'Sucre'],
        ['state' => 'SUCRE', 'name' => 'Valdez'],

        ['state' => 'TACHIRA', 'name' => 'Andrés Bello'],
        ['state' => 'TACHIRA', 'name' => 'Ayacucho'],
        ['state' => 'TACHIRA', 'name' => 'Bolívar'],
        ['state' => 'TACHIRA', 'name' => 'Cárdenas'],
        ['state' => 'TACHIRA', 'name' => 'Córdoba'],
        ['state' => 'TACHIRA', 'name' => 'Francisco de Miranda'],
        ['state' => 'TACHIRA', 'name' => 'Guásimos'],
        ['state' => 'TACHIRA', 'name' => 'Independencia'],
        ['state' => 'TACHIRA', 'name' => 'Jáuregui'],
        ['state' => 'TACHIRA', 'name' => 'José María Vargas'],
        ['state' => 'TACHIRA', 'name' => 'Junín'],
        ['state' => 'TACHIRA', 'name' => 'Libertad'],
        ['state' => 'TACHIRA', 'name' => 'Libertador'],
        ['state' => 'TACHIRA', 'name' => 'Michelena'],
        ['state' => 'TACHIRA', 'name' => 'Pedro María Ureña'],
        ['state' => 'TACHIRA', 'name' => 'Rafael Urdaneta'],
        ['state' => 'TACHIRA', 'name' => 'Samuel Dario Maldonado'],
        ['state' => 'TACHIRA', 'name' => 'San Judas Tadeo'],
        ['state' => 'TACHIRA', 'name' => 'Seboruco'],
        ['state' => 'TACHIRA', 'name' => 'Simón Rodríguez'],
        ['state' => 'TACHIRA', 'name' => 'Sucre'],
        ['state' => 'TACHIRA', 'name' => 'Uribante'],
        ['state' => 'TACHIRA', 'name' => 'Torbes'],
        ['state' => 'TACHIRA', 'name' => 'Panamericano'],
        ['state' => 'TACHIRA', 'name' => 'Fernández Feo'],
        ['state' => 'TACHIRA', 'name' => 'Lobatera'],
        ['state' => 'TACHIRA', 'name' => 'Antonio Rómulo Costa'],
        ['state' => 'TACHIRA', 'name' => 'García de Hevia'],
        ['state' => 'TACHIRA', 'name' => 'San Cristóbal'],

        ['state' => 'TRUJILLO', 'name' => 'Andrés Bello'],
        ['state' => 'TRUJILLO', 'name' => 'boconó'],
        ['state' => 'TRUJILLO', 'name' => 'BOLÍVAR'],
        ['state' => 'TRUJILLO', 'name' => 'CANDELARIA'],
        ['state' => 'TRUJILLO', 'name' => 'carache'],
        ['state' => 'TRUJILLO', 'name' => 'Escuque'],
        ['state' => 'TRUJILLO', 'name' => 'José Felipe Márquez Cañizales'],
        ['state' => 'TRUJILLO', 'name' => 'Juan Vicente Campos Elías'],
        ['state' => 'TRUJILLO', 'name' => 'La Ceiba'],
        ['state' => 'TRUJILLO', 'name' => 'Miranda'],
        ['state' => 'TRUJILLO', 'name' => 'Monte Carmelo'],
        ['state' => 'TRUJILLO', 'name' => 'Motatán'],
        ['state' => 'TRUJILLO', 'name' => 'Pampán'],
        ['state' => 'TRUJILLO', 'name' => 'Pampanito'],
        ['state' => 'TRUJILLO', 'name' => 'Rafael Rangel'],
        ['state' => 'TRUJILLO', 'name' => 'San Rafael de Carvajal'],
        ['state' => 'TRUJILLO', 'name' => 'Sucre'],
        ['state' => 'TRUJILLO', 'name' => 'Trujillo'],
        ['state' => 'TRUJILLO', 'name' => 'Urdaneta'],
        ['state' => 'TRUJILLO', 'name' => 'Valera'],

        ['state' => 'VARGAS', 'name' => 'Vargas'],

        ['state' => 'YARACUY', 'name' => 'Arístides Bastidas'],
        ['state' => 'YARACUY', 'name' => 'Bolívar'],
        ['state' => 'YARACUY', 'name' => 'Bruzual'],
        ['state' => 'YARACUY', 'name' => 'Cocorote'],
        ['state' => 'YARACUY', 'name' => 'Independencia'],
        ['state' => 'YARACUY', 'name' => 'José Antonio Páez'],
        ['state' => 'YARACUY', 'name' => 'La Trinidad'],
        ['state' => 'YARACUY', 'name' => 'Manuel Monge'],
        ['state' => 'YARACUY', 'name' => 'Nirgua'],
        ['state' => 'YARACUY', 'name' => 'Peña'],
        ['state' => 'YARACUY', 'name' => 'San Felipe'],
        ['state' => 'YARACUY', 'name' => 'Sucre'],
        ['state' => 'YARACUY', 'name' => 'Urachiche'],
        ['state' => 'YARACUY', 'name' => 'José Joaquín Veroes'],

        ['state' => 'ZULIA', 'name' => 'Almirante Padilla'],
        ['state' => 'ZULIA', 'name' => 'Baralt'],
        ['state' => 'ZULIA', 'name' => 'Cabimas'],
        ['state' => 'ZULIA', 'name' => 'Catatumbo'],
        ['state' => 'ZULIA', 'name' => 'Colón'],
        ['state' => 'ZULIA', 'name' => 'Francisco Javier Pulgar'],
        ['state' => 'ZULIA', 'name' => 'Jesús Enrique Lossada'],
        ['state' => 'ZULIA', 'name' => 'Jesús María Semprún'],
        ['state' => 'ZULIA', 'name' => 'La Cañada de Urdaneta'],
        ['state' => 'ZULIA', 'name' => 'Lagunillas'],
        ['state' => 'ZULIA', 'name' => 'Machiques de Perijá'],
        ['state' => 'ZULIA', 'name' => 'Mara'],
        ['state' => 'ZULIA', 'name' => 'Maracaibo'],
        ['state' => 'ZULIA', 'name' => 'Miranda'],
        ['state' => 'ZULIA', 'name' => 'Guajira'],
        ['state' => 'ZULIA', 'name' => 'Rosario de Perijá'],
        ['state' => 'ZULIA', 'name' => 'San Francisco'],
        ['state' => 'ZULIA', 'name' => 'Santa Rita'],
        ['state' => 'ZULIA', 'name' => 'Simón Bolívar'],
        ['state' => 'ZULIA', 'name' => 'Sucre'],
        ['state' => 'ZULIA', 'name' => 'Valmore Rodríguez'],

        ['state' => 'DELTA AMACURO', 'name' => 'Antonio Díaz'],
        ['state' => 'DELTA AMACURO', 'name' => 'Casacoima'],
        ['state' => 'DELTA AMACURO', 'name' => 'Pedernales'],
        ['state' => 'DELTA AMACURO', 'name' => 'Tucupita']
    ];
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $states = State::orderBy('id', 'ASC')->select('id', 'name')->get();
        foreach ($this->municipalities as $municipality) {
            foreach ($states as $state) {
                if ($state->name == $municipality['state']) {
                    Municipality::create([
                        'name' => $municipality['name'],
                        'state_id' => $state->id
                    ]);
                    break;
                }
            }
            
        }
    }
}
